modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="stone_plus"
version="0.0.1"
displayName="Stone+"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Joseph Reis"
description="Adds stones from real life into the game."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.stone_plus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration