/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package jr.stoneplus.mod.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import jr.stoneplus.mod.StonePlusMod;

public class StonePlusModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, StonePlusMod.MODID);
	public static final RegistryObject<Item> BASANITE = block(StonePlusModBlocks.BASANITE);
	public static final RegistryObject<Item> GABBRO = block(StonePlusModBlocks.GABBRO);
	public static final RegistryObject<Item> LIMESTONE = block(StonePlusModBlocks.LIMESTONE);
	public static final RegistryObject<Item> MARBLE = block(StonePlusModBlocks.MARBLE);
	public static final RegistryObject<Item> QUARTZITE = block(StonePlusModBlocks.QUARTZITE);
	public static final RegistryObject<Item> SCORIA = block(StonePlusModBlocks.SCORIA);
	public static final RegistryObject<Item> SHALE = block(StonePlusModBlocks.SHALE);
	public static final RegistryObject<Item> SLATE = block(StonePlusModBlocks.SLATE);
	public static final RegistryObject<Item> TRAVERTINE = block(StonePlusModBlocks.TRAVERTINE);
	public static final RegistryObject<Item> GREENSTONE = block(StonePlusModBlocks.GREENSTONE);
	public static final RegistryObject<Item> COBBLED_GABBRO = block(StonePlusModBlocks.COBBLED_GABBRO);
	public static final RegistryObject<Item> COBBLED_SHALE = block(StonePlusModBlocks.COBBLED_SHALE);
	public static final RegistryObject<Item> COBBLED_SLATE = block(StonePlusModBlocks.COBBLED_SLATE);
	public static final RegistryObject<Item> POLISHED_BASANITE = block(StonePlusModBlocks.POLISHED_BASANITE);
	public static final RegistryObject<Item> BASANITE_BRICKS = block(StonePlusModBlocks.BASANITE_BRICKS);
	public static final RegistryObject<Item> POLISHED_LIMESTONE = block(StonePlusModBlocks.POLISHED_LIMESTONE);
	public static final RegistryObject<Item> POLISHED_MARBLE = block(StonePlusModBlocks.POLISHED_MARBLE);
	public static final RegistryObject<Item> POLISHED_QUARTZITE = block(StonePlusModBlocks.POLISHED_QUARTZITE);
	public static final RegistryObject<Item> POLISHED_SCORIA = block(StonePlusModBlocks.POLISHED_SCORIA);
	public static final RegistryObject<Item> SCORIA_BRICKS = block(StonePlusModBlocks.SCORIA_BRICKS);
	public static final RegistryObject<Item> CUT_TRAVERTINE = block(StonePlusModBlocks.CUT_TRAVERTINE);
	public static final RegistryObject<Item> POLISHED_GREENSTONE = block(StonePlusModBlocks.POLISHED_GREENSTONE);
	public static final RegistryObject<Item> POLISHED_BASANITE_STAIRS = block(StonePlusModBlocks.POLISHED_BASANITE_STAIRS);
	public static final RegistryObject<Item> POLISHED_BASANITE_SLAB = block(StonePlusModBlocks.POLISHED_BASANITE_SLAB);
	public static final RegistryObject<Item> POLISHED_BASANITE_WALL = block(StonePlusModBlocks.POLISHED_BASANITE_WALL);
	public static final RegistryObject<Item> POLISHED_LIMESTONE_STAIRS = block(StonePlusModBlocks.POLISHED_LIMESTONE_STAIRS);
	public static final RegistryObject<Item> POLISHED_LIMESTONE_SLAB = block(StonePlusModBlocks.POLISHED_LIMESTONE_SLAB);
	public static final RegistryObject<Item> POLISHED_LIMESTONE_WALL = block(StonePlusModBlocks.POLISHED_LIMESTONE_WALL);
	public static final RegistryObject<Item> POLISHED_MARBLE_STAIRS = block(StonePlusModBlocks.POLISHED_MARBLE_STAIRS);
	public static final RegistryObject<Item> POLISHED_MARBLE_SLAB = block(StonePlusModBlocks.POLISHED_MARBLE_SLAB);
	public static final RegistryObject<Item> POLISHED_MARBLE_WALL = block(StonePlusModBlocks.POLISHED_MARBLE_WALL);
	public static final RegistryObject<Item> POLISHED_QUARTZITE_STAIRS = block(StonePlusModBlocks.POLISHED_QUARTZITE_STAIRS);
	public static final RegistryObject<Item> POLISHED_QUARTZITE_SLAB = block(StonePlusModBlocks.POLISHED_QUARTZITE_SLAB);
	public static final RegistryObject<Item> POLISHED_QUARTZITE_WALL = block(StonePlusModBlocks.POLISHED_QUARTZITE_WALL);
	public static final RegistryObject<Item> POLISHED_SCORIA_STAIRS = block(StonePlusModBlocks.POLISHED_SCORIA_STAIRS);
	public static final RegistryObject<Item> POLISHED_SCORIA_SLAB = block(StonePlusModBlocks.POLISHED_SCORIA_SLAB);
	public static final RegistryObject<Item> POLISHED_SCORIA_WALL = block(StonePlusModBlocks.POLISHED_SCORIA_WALL);
	public static final RegistryObject<Item> CUT_TRAVERTINE_STAIRS = block(StonePlusModBlocks.CUT_TRAVERTINE_STAIRS);
	public static final RegistryObject<Item> CUT_TRAVERTINE_SLAB = block(StonePlusModBlocks.CUT_TRAVERTINE_SLAB);
	public static final RegistryObject<Item> CUT_TRAVERTINE_WALL = block(StonePlusModBlocks.CUT_TRAVERTINE_WALL);
	public static final RegistryObject<Item> POLISHED_GREENSTONE_STAIRS = block(StonePlusModBlocks.POLISHED_GREENSTONE_STAIRS);
	public static final RegistryObject<Item> POLISHED_GREENSTONE_SLAB = block(StonePlusModBlocks.POLISHED_GREENSTONE_SLAB);
	public static final RegistryObject<Item> POLISHED_GREENSTONE_WALL = block(StonePlusModBlocks.POLISHED_GREENSTONE_WALL);
	public static final RegistryObject<Item> ASHSTONE = block(StonePlusModBlocks.ASHSTONE);
	public static final RegistryObject<Item> COBBLED_ASHSTONE = block(StonePlusModBlocks.COBBLED_ASHSTONE);
	public static final RegistryObject<Item> ASHSTONE_BRICKS = block(StonePlusModBlocks.ASHSTONE_BRICKS);
	public static final RegistryObject<Item> ASHSTONE_BRICKS_STAIRS = block(StonePlusModBlocks.ASHSTONE_BRICKS_STAIRS);
	public static final RegistryObject<Item> ASHSTONE_BRICKS_SLAB = block(StonePlusModBlocks.ASHSTONE_BRICKS_SLAB);
	public static final RegistryObject<Item> ASHSTONE_BRICKS_WALL = block(StonePlusModBlocks.ASHSTONE_BRICKS_WALL);
	public static final RegistryObject<Item> ASHSTONE_STAIRS = block(StonePlusModBlocks.ASHSTONE_STAIRS);
	public static final RegistryObject<Item> ASHSTONE_SLAB = block(StonePlusModBlocks.ASHSTONE_SLAB);
	public static final RegistryObject<Item> ASHSTONE_WALL = block(StonePlusModBlocks.ASHSTONE_WALL);
	public static final RegistryObject<Item> COBBLED_ASHSTONE_STAIRS = block(StonePlusModBlocks.COBBLED_ASHSTONE_STAIRS);
	public static final RegistryObject<Item> COBBLED_ASHSTONE_SLAB = block(StonePlusModBlocks.COBBLED_ASHSTONE_SLAB);
	public static final RegistryObject<Item> COBBLED_ASHSTONE_WALL = block(StonePlusModBlocks.COBBLED_ASHSTONE_WALL);
	public static final RegistryObject<Item> CRIMSONSTONE = block(StonePlusModBlocks.CRIMSONSTONE);
	public static final RegistryObject<Item> POLISHED_CRIMSONSTONE = block(StonePlusModBlocks.POLISHED_CRIMSONSTONE);
	public static final RegistryObject<Item> CRIMSONSTONE_BRICKS = block(StonePlusModBlocks.CRIMSONSTONE_BRICKS);
	public static final RegistryObject<Item> POLISHED_CRIMSONSTONE_STAIRS = block(StonePlusModBlocks.POLISHED_CRIMSONSTONE_STAIRS);
	public static final RegistryObject<Item> POLISHED_CRIMSONSTONE_SLAB = block(StonePlusModBlocks.POLISHED_CRIMSONSTONE_SLAB);
	public static final RegistryObject<Item> POLISHED_CRIMSONSTONE_WALL = block(StonePlusModBlocks.POLISHED_CRIMSONSTONE_WALL);
	public static final RegistryObject<Item> CRIMSONSTONE_BRICKS_STAIRS = block(StonePlusModBlocks.CRIMSONSTONE_BRICKS_STAIRS);
	public static final RegistryObject<Item> CRIMSONSTONE_BRICKS_SLAB = block(StonePlusModBlocks.CRIMSONSTONE_BRICKS_SLAB);
	public static final RegistryObject<Item> CRIMSONSTONE_BRICKS_WALL = block(StonePlusModBlocks.CRIMSONSTONE_BRICKS_WALL);
	public static final RegistryObject<Item> CRIMSONSTONE_STAIRS = block(StonePlusModBlocks.CRIMSONSTONE_STAIRS);
	public static final RegistryObject<Item> CRIMSONSTONE_SLAB = block(StonePlusModBlocks.CRIMSONSTONE_SLAB);
	public static final RegistryObject<Item> CRIMSONSTONE_WALL = block(StonePlusModBlocks.CRIMSONSTONE_WALL);
	public static final RegistryObject<Item> DARK_BASALTSTONE = block(StonePlusModBlocks.DARK_BASALTSTONE);
	public static final RegistryObject<Item> DARK_BASALTSTONE_BRICKS = block(StonePlusModBlocks.DARK_BASALTSTONE_BRICKS);
	public static final RegistryObject<Item> POLISHED_DARK_BASALTSTONE = block(StonePlusModBlocks.POLISHED_DARK_BASALTSTONE);
	public static final RegistryObject<Item> DARK_BASALTSTONE_STAIRS = block(StonePlusModBlocks.DARK_BASALTSTONE_STAIRS);
	public static final RegistryObject<Item> DARK_BASALTSTONE_SLAB = block(StonePlusModBlocks.DARK_BASALTSTONE_SLAB);
	public static final RegistryObject<Item> DARK_BASALTSTONE_WALL = block(StonePlusModBlocks.DARK_BASALTSTONE_WALL);
	public static final RegistryObject<Item> POLISHED_DARK_BASALTSTONE_STAIRS = block(StonePlusModBlocks.POLISHED_DARK_BASALTSTONE_STAIRS);
	public static final RegistryObject<Item> POLISHED_DARK_BASALTSTONE_SLAB = block(StonePlusModBlocks.POLISHED_DARK_BASALTSTONE_SLAB);
	public static final RegistryObject<Item> POLISHED_DARK_BASALTSTONE_WALL = block(StonePlusModBlocks.POLISHED_DARK_BASALTSTONE_WALL);
	public static final RegistryObject<Item> DARK_BASALTSTONE_BRICKS_STAIRS = block(StonePlusModBlocks.DARK_BASALTSTONE_BRICKS_STAIRS);
	public static final RegistryObject<Item> DARK_BASALTSTONE_BRICKS_SLAB = block(StonePlusModBlocks.DARK_BASALTSTONE_BRICKS_SLAB);
	public static final RegistryObject<Item> DARK_BASALTSTONE_BRICKS_WALL = block(StonePlusModBlocks.DARK_BASALTSTONE_BRICKS_WALL);
	public static final RegistryObject<Item> DEEPDAY = block(StonePlusModBlocks.DEEPDAY);
	public static final RegistryObject<Item> COBBLED_DEEPDAY = block(StonePlusModBlocks.COBBLED_DEEPDAY);
	public static final RegistryObject<Item> POLISHED_DEEPDAY = block(StonePlusModBlocks.POLISHED_DEEPDAY);
	public static final RegistryObject<Item> DEEPDAY_BRICKS = block(StonePlusModBlocks.DEEPDAY_BRICKS);
	public static final RegistryObject<Item> DEEPDAY_TILES = block(StonePlusModBlocks.DEEPDAY_TILES);
	public static final RegistryObject<Item> DEEPDAY_STAIRS = block(StonePlusModBlocks.DEEPDAY_STAIRS);
	public static final RegistryObject<Item> DEEPDAY_SLAB = block(StonePlusModBlocks.DEEPDAY_SLAB);
	public static final RegistryObject<Item> DEEPDAY_WALL = block(StonePlusModBlocks.DEEPDAY_WALL);
	public static final RegistryObject<Item> POLISHED_DEEPDAY_STAIRS = block(StonePlusModBlocks.POLISHED_DEEPDAY_STAIRS);
	public static final RegistryObject<Item> POLISHED_DEEPDAY_SLAB = block(StonePlusModBlocks.POLISHED_DEEPDAY_SLAB);
	public static final RegistryObject<Item> POLISHED_DEEPDAY_WALL = block(StonePlusModBlocks.POLISHED_DEEPDAY_WALL);
	public static final RegistryObject<Item> DEEPDAY_BRICKS_STAIRS = block(StonePlusModBlocks.DEEPDAY_BRICKS_STAIRS);
	public static final RegistryObject<Item> DEEPDAY_BRICKS_SLAB = block(StonePlusModBlocks.DEEPDAY_BRICKS_SLAB);
	public static final RegistryObject<Item> DEEPDAY_BRICKS_WALL = block(StonePlusModBlocks.DEEPDAY_BRICKS_WALL);
	public static final RegistryObject<Item> DEEPDAY_TILES_STAIRS = block(StonePlusModBlocks.DEEPDAY_TILES_STAIRS);
	public static final RegistryObject<Item> DEEPDAY_TILES_SLAB = block(StonePlusModBlocks.DEEPDAY_TILES_SLAB);
	public static final RegistryObject<Item> DEEPDAY_TILES_WALL = block(StonePlusModBlocks.DEEPDAY_TILES_WALL);
	public static final RegistryObject<Item> COBBLED_DEEPDAY_STAIRS = block(StonePlusModBlocks.COBBLED_DEEPDAY_STAIRS);
	public static final RegistryObject<Item> COBBLED_DEEPDAY_SLAB = block(StonePlusModBlocks.COBBLED_DEEPDAY_SLAB);
	public static final RegistryObject<Item> COBBLED_DEEPDAY_WALL = block(StonePlusModBlocks.COBBLED_DEEPDAY_WALL);
	public static final RegistryObject<Item> FROSTSTONE = block(StonePlusModBlocks.FROSTSTONE);
	public static final RegistryObject<Item> POLISHED_FROSTSTONE = block(StonePlusModBlocks.POLISHED_FROSTSTONE);
	public static final RegistryObject<Item> FROSTSTONE_STAIRS = block(StonePlusModBlocks.FROSTSTONE_STAIRS);
	public static final RegistryObject<Item> FROSTSTONE_SLAB = block(StonePlusModBlocks.FROSTSTONE_SLAB);
	public static final RegistryObject<Item> FROSTSTONE_WALL = block(StonePlusModBlocks.FROSTSTONE_WALL);
	public static final RegistryObject<Item> POLISHED_FROSTSTONE_STAIRS = block(StonePlusModBlocks.POLISHED_FROSTSTONE_STAIRS);
	public static final RegistryObject<Item> POLISHED_FROSTSTONE_SLAB = block(StonePlusModBlocks.POLISHED_FROSTSTONE_SLAB);
	public static final RegistryObject<Item> POLISHED_FROSTSTONE_WALL = block(StonePlusModBlocks.POLISHED_FROSTSTONE_WALL);
	public static final RegistryObject<Item> MUDSTONE = block(StonePlusModBlocks.MUDSTONE);
	public static final RegistryObject<Item> COBBLED_MUDSTONE = block(StonePlusModBlocks.COBBLED_MUDSTONE);
	public static final RegistryObject<Item> MUDSTONE_BRICKS = block(StonePlusModBlocks.MUDSTONE_BRICKS);
	public static final RegistryObject<Item> MUDSTONE_STAIRS = block(StonePlusModBlocks.MUDSTONE_STAIRS);
	public static final RegistryObject<Item> MUDSTONE_SLAB = block(StonePlusModBlocks.MUDSTONE_SLAB);
	public static final RegistryObject<Item> MUDSTONE_WALL = block(StonePlusModBlocks.MUDSTONE_WALL);
	public static final RegistryObject<Item> COBBLED_MUDSTONE_STAIRS = block(StonePlusModBlocks.COBBLED_MUDSTONE_STAIRS);
	public static final RegistryObject<Item> COBBLED_MUDSTONE_SLAB = block(StonePlusModBlocks.COBBLED_MUDSTONE_SLAB);
	public static final RegistryObject<Item> COBBLED_MUDSTONE_WALL = block(StonePlusModBlocks.COBBLED_MUDSTONE_WALL);
	public static final RegistryObject<Item> MUDSTONE_BRICKS_STAIRS = block(StonePlusModBlocks.MUDSTONE_BRICKS_STAIRS);
	public static final RegistryObject<Item> MUDSTONE_BRICKS_SLAB = block(StonePlusModBlocks.MUDSTONE_BRICKS_SLAB);
	public static final RegistryObject<Item> MUDSTONE_BRICKS_WALL = block(StonePlusModBlocks.MUDSTONE_BRICKS_WALL);
	public static final RegistryObject<Item> ROSESTONE = block(StonePlusModBlocks.ROSESTONE);
	public static final RegistryObject<Item> POLISHED_ROSESTONE = block(StonePlusModBlocks.POLISHED_ROSESTONE);
	public static final RegistryObject<Item> ROSESTONE_STAIRS = block(StonePlusModBlocks.ROSESTONE_STAIRS);
	public static final RegistryObject<Item> ROSESTONE_SLAB = block(StonePlusModBlocks.ROSESTONE_SLAB);
	public static final RegistryObject<Item> ROSESTONE_WALL = block(StonePlusModBlocks.ROSESTONE_WALL);
	public static final RegistryObject<Item> POLISHED_ROSESTONE_STAIRS = block(StonePlusModBlocks.POLISHED_ROSESTONE_STAIRS);
	public static final RegistryObject<Item> POLISHED_ROSESTONE_SLAB = block(StonePlusModBlocks.POLISHED_ROSESTONE_SLAB);
	public static final RegistryObject<Item> POLISHED_ROSESTONE_WAL = block(StonePlusModBlocks.POLISHED_ROSESTONE_WAL);
	public static final RegistryObject<Item> SILTSTONE = block(StonePlusModBlocks.SILTSTONE);
	public static final RegistryObject<Item> CUT_SILTSTONE = block(StonePlusModBlocks.CUT_SILTSTONE);
	public static final RegistryObject<Item> SILTSTONE_STAIRS = block(StonePlusModBlocks.SILTSTONE_STAIRS);
	public static final RegistryObject<Item> SILTSTONE_SLAB = block(StonePlusModBlocks.SILTSTONE_SLAB);
	public static final RegistryObject<Item> SILTSTONE_WALL = block(StonePlusModBlocks.SILTSTONE_WALL);
	public static final RegistryObject<Item> CUT_SILTSTONE_STAIRS = block(StonePlusModBlocks.CUT_SILTSTONE_STAIRS);
	public static final RegistryObject<Item> CUT_SILTSTONE_SLAB = block(StonePlusModBlocks.CUT_SILTSTONE_SLAB);
	public static final RegistryObject<Item> CUT_SILTSTONE_WALL = block(StonePlusModBlocks.CUT_SILTSTONE_WALL);
	public static final RegistryObject<Item> SUNSTONE = block(StonePlusModBlocks.SUNSTONE);
	public static final RegistryObject<Item> CUT_SUNSTONE = block(StonePlusModBlocks.CUT_SUNSTONE);
	public static final RegistryObject<Item> SUNSTONE_STAIRS = block(StonePlusModBlocks.SUNSTONE_STAIRS);
	public static final RegistryObject<Item> SUNSTONE_SLAB = block(StonePlusModBlocks.SUNSTONE_SLAB);
	public static final RegistryObject<Item> SUNSTONE_WALL = block(StonePlusModBlocks.SUNSTONE_WALL);
	public static final RegistryObject<Item> CUT_SUNSTONE_STAIRS = block(StonePlusModBlocks.CUT_SUNSTONE_STAIRS);
	public static final RegistryObject<Item> CUT_SUNSTONE_SLAB = block(StonePlusModBlocks.CUT_SUNSTONE_SLAB);
	public static final RegistryObject<Item> CUT_SUNSTONE_WALL = block(StonePlusModBlocks.CUT_SUNSTONE_WALL);
	public static final RegistryObject<Item> GABBRO_STAIRS = block(StonePlusModBlocks.GABBRO_STAIRS);
	public static final RegistryObject<Item> GABBRO_SLAB = block(StonePlusModBlocks.GABBRO_SLAB);
	public static final RegistryObject<Item> GABBRO_WALL = block(StonePlusModBlocks.GABBRO_WALL);
	public static final RegistryObject<Item> BASANITE_STAIRS = block(StonePlusModBlocks.BASANITE_STAIRS);
	public static final RegistryObject<Item> BASANITE_SLAB = block(StonePlusModBlocks.BASANITE_SLAB);
	public static final RegistryObject<Item> BASANITE_WALL = block(StonePlusModBlocks.BASANITE_WALL);
	public static final RegistryObject<Item> BASANITE_BRICKS_STAIRS = block(StonePlusModBlocks.BASANITE_BRICKS_STAIRS);
	public static final RegistryObject<Item> BASANITE_BRICKS_SLAB = block(StonePlusModBlocks.BASANITE_BRICKS_SLAB);
	public static final RegistryObject<Item> BASANITE_BRICKS_WALL = block(StonePlusModBlocks.BASANITE_BRICKS_WALL);
	public static final RegistryObject<Item> LIMESTONE_STAIRS = block(StonePlusModBlocks.LIMESTONE_STAIRS);
	public static final RegistryObject<Item> LIMESTONE_SLAB = block(StonePlusModBlocks.LIMESTONE_SLAB);
	public static final RegistryObject<Item> LIMESTONE_WALL = block(StonePlusModBlocks.LIMESTONE_WALL);
	public static final RegistryObject<Item> MARBLE_STAIRS = block(StonePlusModBlocks.MARBLE_STAIRS);
	public static final RegistryObject<Item> MARBLE_SLAB = block(StonePlusModBlocks.MARBLE_SLAB);
	public static final RegistryObject<Item> MARBLE_WALL = block(StonePlusModBlocks.MARBLE_WALL);
	public static final RegistryObject<Item> QUARTZITE_STAIRS = block(StonePlusModBlocks.QUARTZITE_STAIRS);
	public static final RegistryObject<Item> QUARTZITE_SLAB = block(StonePlusModBlocks.QUARTZITE_SLAB);
	public static final RegistryObject<Item> QUARTZITE_WALL = block(StonePlusModBlocks.QUARTZITE_WALL);
	public static final RegistryObject<Item> SCORIA_STAIRS = block(StonePlusModBlocks.SCORIA_STAIRS);
	public static final RegistryObject<Item> SCORIA_SLAB = block(StonePlusModBlocks.SCORIA_SLAB);
	public static final RegistryObject<Item> SCORIA_WALL = block(StonePlusModBlocks.SCORIA_WALL);
	public static final RegistryObject<Item> SCORIA_BRICKS_STAIRS = block(StonePlusModBlocks.SCORIA_BRICKS_STAIRS);
	public static final RegistryObject<Item> SCORIA_BRICKS_SLAB = block(StonePlusModBlocks.SCORIA_BRICKS_SLAB);
	public static final RegistryObject<Item> SCORIA_BRICKS_WALL = block(StonePlusModBlocks.SCORIA_BRICKS_WALL);
	public static final RegistryObject<Item> SHALE_STAIRS = block(StonePlusModBlocks.SHALE_STAIRS);
	public static final RegistryObject<Item> SHALE_SLAB = block(StonePlusModBlocks.SHALE_SLAB);
	public static final RegistryObject<Item> SHALE_WALL = block(StonePlusModBlocks.SHALE_WALL);
	public static final RegistryObject<Item> COBBLED_SHALE_STAIRS = block(StonePlusModBlocks.COBBLED_SHALE_STAIRS);
	public static final RegistryObject<Item> COBBLED_SHALE_SLAB = block(StonePlusModBlocks.COBBLED_SHALE_SLAB);
	public static final RegistryObject<Item> COBBLED_SHALE_WALL = block(StonePlusModBlocks.COBBLED_SHALE_WALL);
	public static final RegistryObject<Item> SHALE_BRICKS = block(StonePlusModBlocks.SHALE_BRICKS);
	public static final RegistryObject<Item> SHALE_BRICKS_STAIRS = block(StonePlusModBlocks.SHALE_BRICKS_STAIRS);
	public static final RegistryObject<Item> SHALE_BRICKS_SLAB = block(StonePlusModBlocks.SHALE_BRICKS_SLAB);
	public static final RegistryObject<Item> SHALE_BRICKS_WALL = block(StonePlusModBlocks.SHALE_BRICKS_WALL);
	public static final RegistryObject<Item> SLATE_BRICKS = block(StonePlusModBlocks.SLATE_BRICKS);
	public static final RegistryObject<Item> SLATE_STAIRS = block(StonePlusModBlocks.SLATE_STAIRS);
	public static final RegistryObject<Item> SLATE_SLAB = block(StonePlusModBlocks.SLATE_SLAB);
	public static final RegistryObject<Item> SLATE_WALL = block(StonePlusModBlocks.SLATE_WALL);
	public static final RegistryObject<Item> COBBLED_SLATE_SLAB = block(StonePlusModBlocks.COBBLED_SLATE_SLAB);
	public static final RegistryObject<Item> COBBLED_SLATE_STAIRS = block(StonePlusModBlocks.COBBLED_SLATE_STAIRS);
	public static final RegistryObject<Item> COBBLED_SLATE_WALL = block(StonePlusModBlocks.COBBLED_SLATE_WALL);
	public static final RegistryObject<Item> SLATE_BRICKS_STAIRS = block(StonePlusModBlocks.SLATE_BRICKS_STAIRS);
	public static final RegistryObject<Item> SLATE_BRICKS_SLAB = block(StonePlusModBlocks.SLATE_BRICKS_SLAB);
	public static final RegistryObject<Item> SLATE_BRICKS_WALL = block(StonePlusModBlocks.SLATE_BRICKS_WALL);
	public static final RegistryObject<Item> TRAVERTINE_STAIRS = block(StonePlusModBlocks.TRAVERTINE_STAIRS);
	public static final RegistryObject<Item> TRAVERTINE_SLAB = block(StonePlusModBlocks.TRAVERTINE_SLAB);
	public static final RegistryObject<Item> TRAVERTINE_WALL = block(StonePlusModBlocks.TRAVERTINE_WALL);
	public static final RegistryObject<Item> GREENSTONE_STAIRS = block(StonePlusModBlocks.GREENSTONE_STAIRS);
	public static final RegistryObject<Item> GREENSTONE_SLAB = block(StonePlusModBlocks.GREENSTONE_SLAB);
	public static final RegistryObject<Item> GREENSTONE_WALL = block(StonePlusModBlocks.GREENSTONE_WALL);

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return block(block, new Item.Properties());
	}

	private static RegistryObject<Item> block(RegistryObject<Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), properties));
	}
}