/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package jr.stoneplus.mod.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import jr.stoneplus.mod.block.TravertineWallBlock;
import jr.stoneplus.mod.block.TravertineStairsBlock;
import jr.stoneplus.mod.block.TravertineSlabBlock;
import jr.stoneplus.mod.block.TravertineBlock;
import jr.stoneplus.mod.block.SunstoneWallBlock;
import jr.stoneplus.mod.block.SunstoneStairsBlock;
import jr.stoneplus.mod.block.SunstoneSlabBlock;
import jr.stoneplus.mod.block.SunstoneBlock;
import jr.stoneplus.mod.block.SlateWallBlock;
import jr.stoneplus.mod.block.SlateStairsBlock;
import jr.stoneplus.mod.block.SlateSlabBlock;
import jr.stoneplus.mod.block.SlateBricksWallBlock;
import jr.stoneplus.mod.block.SlateBricksStairsBlock;
import jr.stoneplus.mod.block.SlateBricksSlabBlock;
import jr.stoneplus.mod.block.SlateBricksBlock;
import jr.stoneplus.mod.block.SlateBlock;
import jr.stoneplus.mod.block.SiltstoneWallBlock;
import jr.stoneplus.mod.block.SiltstoneStairsBlock;
import jr.stoneplus.mod.block.SiltstoneSlabBlock;
import jr.stoneplus.mod.block.SiltstoneBlock;
import jr.stoneplus.mod.block.ShaleWallBlock;
import jr.stoneplus.mod.block.ShaleStairsBlock;
import jr.stoneplus.mod.block.ShaleSlabBlock;
import jr.stoneplus.mod.block.ShaleBricksWallBlock;
import jr.stoneplus.mod.block.ShaleBricksStairsBlock;
import jr.stoneplus.mod.block.ShaleBricksSlabBlock;
import jr.stoneplus.mod.block.ShaleBricksBlock;
import jr.stoneplus.mod.block.ShaleBlock;
import jr.stoneplus.mod.block.ScoriaWallBlock;
import jr.stoneplus.mod.block.ScoriaStairsBlock;
import jr.stoneplus.mod.block.ScoriaSlabBlock;
import jr.stoneplus.mod.block.ScoriaBricksWallBlock;
import jr.stoneplus.mod.block.ScoriaBricksStairsBlock;
import jr.stoneplus.mod.block.ScoriaBricksSlabBlock;
import jr.stoneplus.mod.block.ScoriaBricksBlock;
import jr.stoneplus.mod.block.ScoriaBlock;
import jr.stoneplus.mod.block.RosestoneWallBlock;
import jr.stoneplus.mod.block.RosestoneStairsBlock;
import jr.stoneplus.mod.block.RosestoneSlabBlock;
import jr.stoneplus.mod.block.RosestoneBlock;
import jr.stoneplus.mod.block.QuartziteWallBlock;
import jr.stoneplus.mod.block.QuartziteStairsBlock;
import jr.stoneplus.mod.block.QuartziteSlabBlock;
import jr.stoneplus.mod.block.QuartziteBlock;
import jr.stoneplus.mod.block.PolishedScoriaWallBlock;
import jr.stoneplus.mod.block.PolishedScoriaStairsBlock;
import jr.stoneplus.mod.block.PolishedScoriaSlabBlock;
import jr.stoneplus.mod.block.PolishedScoriaBlock;
import jr.stoneplus.mod.block.PolishedRosestoneWalBlock;
import jr.stoneplus.mod.block.PolishedRosestoneStairsBlock;
import jr.stoneplus.mod.block.PolishedRosestoneSlabBlock;
import jr.stoneplus.mod.block.PolishedRosestoneBlock;
import jr.stoneplus.mod.block.PolishedQuartziteWallBlock;
import jr.stoneplus.mod.block.PolishedQuartziteStairsBlock;
import jr.stoneplus.mod.block.PolishedQuartziteSlabBlock;
import jr.stoneplus.mod.block.PolishedQuartziteBlock;
import jr.stoneplus.mod.block.PolishedMarbleWallBlock;
import jr.stoneplus.mod.block.PolishedMarbleStairsBlock;
import jr.stoneplus.mod.block.PolishedMarbleSlabBlock;
import jr.stoneplus.mod.block.PolishedMarbleBlock;
import jr.stoneplus.mod.block.PolishedLimestoneWallBlock;
import jr.stoneplus.mod.block.PolishedLimestoneStairsBlock;
import jr.stoneplus.mod.block.PolishedLimestoneSlabBlock;
import jr.stoneplus.mod.block.PolishedLimestoneBlock;
import jr.stoneplus.mod.block.PolishedGreenstoneWallBlock;
import jr.stoneplus.mod.block.PolishedGreenstoneStairsBlock;
import jr.stoneplus.mod.block.PolishedGreenstoneSlabBlock;
import jr.stoneplus.mod.block.PolishedGreenstoneBlock;
import jr.stoneplus.mod.block.PolishedFroststoneWallBlock;
import jr.stoneplus.mod.block.PolishedFroststoneStairsBlock;
import jr.stoneplus.mod.block.PolishedFroststoneSlabBlock;
import jr.stoneplus.mod.block.PolishedFroststoneBlock;
import jr.stoneplus.mod.block.PolishedDeepdayWallBlock;
import jr.stoneplus.mod.block.PolishedDeepdayStairsBlock;
import jr.stoneplus.mod.block.PolishedDeepdaySlabBlock;
import jr.stoneplus.mod.block.PolishedDeepdayBlock;
import jr.stoneplus.mod.block.PolishedDarkBasaltstoneWallBlock;
import jr.stoneplus.mod.block.PolishedDarkBasaltstoneStairsBlock;
import jr.stoneplus.mod.block.PolishedDarkBasaltstoneSlabBlock;
import jr.stoneplus.mod.block.PolishedDarkBasaltstoneBlock;
import jr.stoneplus.mod.block.PolishedCrimsonstoneWallBlock;
import jr.stoneplus.mod.block.PolishedCrimsonstoneStairsBlock;
import jr.stoneplus.mod.block.PolishedCrimsonstoneSlabBlock;
import jr.stoneplus.mod.block.PolishedCrimsonstoneBlock;
import jr.stoneplus.mod.block.PolishedBasaniteWallBlock;
import jr.stoneplus.mod.block.PolishedBasaniteStairsBlock;
import jr.stoneplus.mod.block.PolishedBasaniteSlabBlock;
import jr.stoneplus.mod.block.PolishedBasaniteBlock;
import jr.stoneplus.mod.block.MudstoneWallBlock;
import jr.stoneplus.mod.block.MudstoneStairsBlock;
import jr.stoneplus.mod.block.MudstoneSlabBlock;
import jr.stoneplus.mod.block.MudstoneBricksWallBlock;
import jr.stoneplus.mod.block.MudstoneBricksStairsBlock;
import jr.stoneplus.mod.block.MudstoneBricksSlabBlock;
import jr.stoneplus.mod.block.MudstoneBricksBlock;
import jr.stoneplus.mod.block.MudstoneBlock;
import jr.stoneplus.mod.block.MarbleWallBlock;
import jr.stoneplus.mod.block.MarbleStairsBlock;
import jr.stoneplus.mod.block.MarbleSlabBlock;
import jr.stoneplus.mod.block.MarbleBlock;
import jr.stoneplus.mod.block.LimestoneWallBlock;
import jr.stoneplus.mod.block.LimestoneStairsBlock;
import jr.stoneplus.mod.block.LimestoneSlabBlock;
import jr.stoneplus.mod.block.LimestoneBlock;
import jr.stoneplus.mod.block.GreenstoneWallBlock;
import jr.stoneplus.mod.block.GreenstoneStairsBlock;
import jr.stoneplus.mod.block.GreenstoneSlabBlock;
import jr.stoneplus.mod.block.GreenstoneBlock;
import jr.stoneplus.mod.block.GabbroWallBlock;
import jr.stoneplus.mod.block.GabbroStairsBlock;
import jr.stoneplus.mod.block.GabbroSlabBlock;
import jr.stoneplus.mod.block.GabbroBlock;
import jr.stoneplus.mod.block.FroststoneWallBlock;
import jr.stoneplus.mod.block.FroststoneStairsBlock;
import jr.stoneplus.mod.block.FroststoneSlabBlock;
import jr.stoneplus.mod.block.FroststoneBlock;
import jr.stoneplus.mod.block.DeepdayWallBlock;
import jr.stoneplus.mod.block.DeepdayTilesWallBlock;
import jr.stoneplus.mod.block.DeepdayTilesStairsBlock;
import jr.stoneplus.mod.block.DeepdayTilesSlabBlock;
import jr.stoneplus.mod.block.DeepdayTilesBlock;
import jr.stoneplus.mod.block.DeepdayStairsBlock;
import jr.stoneplus.mod.block.DeepdaySlabBlock;
import jr.stoneplus.mod.block.DeepdayBricksWallBlock;
import jr.stoneplus.mod.block.DeepdayBricksStairsBlock;
import jr.stoneplus.mod.block.DeepdayBricksSlabBlock;
import jr.stoneplus.mod.block.DeepdayBricksBlock;
import jr.stoneplus.mod.block.DeepdayBlock;
import jr.stoneplus.mod.block.DarkBasaltstoneWallBlock;
import jr.stoneplus.mod.block.DarkBasaltstoneStairsBlock;
import jr.stoneplus.mod.block.DarkBasaltstoneSlabBlock;
import jr.stoneplus.mod.block.DarkBasaltstoneBricksWallBlock;
import jr.stoneplus.mod.block.DarkBasaltstoneBricksStairsBlock;
import jr.stoneplus.mod.block.DarkBasaltstoneBricksSlabBlock;
import jr.stoneplus.mod.block.DarkBasaltstoneBricksBlock;
import jr.stoneplus.mod.block.DarkBasaltstoneBlock;
import jr.stoneplus.mod.block.CutTravertineWallBlock;
import jr.stoneplus.mod.block.CutTravertineStairsBlock;
import jr.stoneplus.mod.block.CutTravertineSlabBlock;
import jr.stoneplus.mod.block.CutTravertineBlock;
import jr.stoneplus.mod.block.CutSunstoneWallBlock;
import jr.stoneplus.mod.block.CutSunstoneStairsBlock;
import jr.stoneplus.mod.block.CutSunstoneSlabBlock;
import jr.stoneplus.mod.block.CutSunstoneBlock;
import jr.stoneplus.mod.block.CutSiltstoneWallBlock;
import jr.stoneplus.mod.block.CutSiltstoneStairsBlock;
import jr.stoneplus.mod.block.CutSiltstoneSlabBlock;
import jr.stoneplus.mod.block.CutSiltstoneBlock;
import jr.stoneplus.mod.block.CrimsonstoneWallBlock;
import jr.stoneplus.mod.block.CrimsonstoneStairsBlock;
import jr.stoneplus.mod.block.CrimsonstoneSlabBlock;
import jr.stoneplus.mod.block.CrimsonstoneBricksWallBlock;
import jr.stoneplus.mod.block.CrimsonstoneBricksStairsBlock;
import jr.stoneplus.mod.block.CrimsonstoneBricksSlabBlock;
import jr.stoneplus.mod.block.CrimsonstoneBricksBlock;
import jr.stoneplus.mod.block.CrimsonstoneBlock;
import jr.stoneplus.mod.block.CobbledSlateWallBlock;
import jr.stoneplus.mod.block.CobbledSlateStairsBlock;
import jr.stoneplus.mod.block.CobbledSlateSlabBlock;
import jr.stoneplus.mod.block.CobbledSlateBlock;
import jr.stoneplus.mod.block.CobbledShaleWallBlock;
import jr.stoneplus.mod.block.CobbledShaleStairsBlock;
import jr.stoneplus.mod.block.CobbledShaleSlabBlock;
import jr.stoneplus.mod.block.CobbledShaleBlock;
import jr.stoneplus.mod.block.CobbledMudstoneWallBlock;
import jr.stoneplus.mod.block.CobbledMudstoneStairsBlock;
import jr.stoneplus.mod.block.CobbledMudstoneSlabBlock;
import jr.stoneplus.mod.block.CobbledMudstoneBlock;
import jr.stoneplus.mod.block.CobbledGabbroBlock;
import jr.stoneplus.mod.block.CobbledDeepdayWallBlock;
import jr.stoneplus.mod.block.CobbledDeepdayStairsBlock;
import jr.stoneplus.mod.block.CobbledDeepdaySlabBlock;
import jr.stoneplus.mod.block.CobbledDeepdayBlock;
import jr.stoneplus.mod.block.CobbledAshstoneWallBlock;
import jr.stoneplus.mod.block.CobbledAshstoneStairsBlock;
import jr.stoneplus.mod.block.CobbledAshstoneSlabBlock;
import jr.stoneplus.mod.block.CobbledAshstoneBlock;
import jr.stoneplus.mod.block.BasaniteWallBlock;
import jr.stoneplus.mod.block.BasaniteStairsBlock;
import jr.stoneplus.mod.block.BasaniteSlabBlock;
import jr.stoneplus.mod.block.BasaniteBricksWallBlock;
import jr.stoneplus.mod.block.BasaniteBricksStairsBlock;
import jr.stoneplus.mod.block.BasaniteBricksSlabBlock;
import jr.stoneplus.mod.block.BasaniteBricksBlock;
import jr.stoneplus.mod.block.BasaniteBlock;
import jr.stoneplus.mod.block.AshstoneWallBlock;
import jr.stoneplus.mod.block.AshstoneStairsBlock;
import jr.stoneplus.mod.block.AshstoneSlabBlock;
import jr.stoneplus.mod.block.AshstoneBricksWallBlock;
import jr.stoneplus.mod.block.AshstoneBricksStairsBlock;
import jr.stoneplus.mod.block.AshstoneBricksSlabBlock;
import jr.stoneplus.mod.block.AshstoneBricksBlock;
import jr.stoneplus.mod.block.AshstoneBlock;
import jr.stoneplus.mod.StonePlusMod;

public class StonePlusModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, StonePlusMod.MODID);
	public static final RegistryObject<Block> BASANITE = REGISTRY.register("basanite", () -> new BasaniteBlock());
	public static final RegistryObject<Block> GABBRO = REGISTRY.register("gabbro", () -> new GabbroBlock());
	public static final RegistryObject<Block> LIMESTONE = REGISTRY.register("limestone", () -> new LimestoneBlock());
	public static final RegistryObject<Block> MARBLE = REGISTRY.register("marble", () -> new MarbleBlock());
	public static final RegistryObject<Block> QUARTZITE = REGISTRY.register("quartzite", () -> new QuartziteBlock());
	public static final RegistryObject<Block> SCORIA = REGISTRY.register("scoria", () -> new ScoriaBlock());
	public static final RegistryObject<Block> SHALE = REGISTRY.register("shale", () -> new ShaleBlock());
	public static final RegistryObject<Block> SLATE = REGISTRY.register("slate", () -> new SlateBlock());
	public static final RegistryObject<Block> TRAVERTINE = REGISTRY.register("travertine", () -> new TravertineBlock());
	public static final RegistryObject<Block> GREENSTONE = REGISTRY.register("greenstone", () -> new GreenstoneBlock());
	public static final RegistryObject<Block> COBBLED_GABBRO = REGISTRY.register("cobbled_gabbro", () -> new CobbledGabbroBlock());
	public static final RegistryObject<Block> COBBLED_SHALE = REGISTRY.register("cobbled_shale", () -> new CobbledShaleBlock());
	public static final RegistryObject<Block> COBBLED_SLATE = REGISTRY.register("cobbled_slate", () -> new CobbledSlateBlock());
	public static final RegistryObject<Block> POLISHED_BASANITE = REGISTRY.register("polished_basanite", () -> new PolishedBasaniteBlock());
	public static final RegistryObject<Block> BASANITE_BRICKS = REGISTRY.register("basanite_bricks", () -> new BasaniteBricksBlock());
	public static final RegistryObject<Block> POLISHED_LIMESTONE = REGISTRY.register("polished_limestone", () -> new PolishedLimestoneBlock());
	public static final RegistryObject<Block> POLISHED_MARBLE = REGISTRY.register("polished_marble", () -> new PolishedMarbleBlock());
	public static final RegistryObject<Block> POLISHED_QUARTZITE = REGISTRY.register("polished_quartzite", () -> new PolishedQuartziteBlock());
	public static final RegistryObject<Block> POLISHED_SCORIA = REGISTRY.register("polished_scoria", () -> new PolishedScoriaBlock());
	public static final RegistryObject<Block> SCORIA_BRICKS = REGISTRY.register("scoria_bricks", () -> new ScoriaBricksBlock());
	public static final RegistryObject<Block> CUT_TRAVERTINE = REGISTRY.register("cut_travertine", () -> new CutTravertineBlock());
	public static final RegistryObject<Block> POLISHED_GREENSTONE = REGISTRY.register("polished_greenstone", () -> new PolishedGreenstoneBlock());
	public static final RegistryObject<Block> POLISHED_BASANITE_STAIRS = REGISTRY.register("polished_basanite_stairs", () -> new PolishedBasaniteStairsBlock());
	public static final RegistryObject<Block> POLISHED_BASANITE_SLAB = REGISTRY.register("polished_basanite_slab", () -> new PolishedBasaniteSlabBlock());
	public static final RegistryObject<Block> POLISHED_BASANITE_WALL = REGISTRY.register("polished_basanite_wall", () -> new PolishedBasaniteWallBlock());
	public static final RegistryObject<Block> POLISHED_LIMESTONE_STAIRS = REGISTRY.register("polished_limestone_stairs", () -> new PolishedLimestoneStairsBlock());
	public static final RegistryObject<Block> POLISHED_LIMESTONE_SLAB = REGISTRY.register("polished_limestone_slab", () -> new PolishedLimestoneSlabBlock());
	public static final RegistryObject<Block> POLISHED_LIMESTONE_WALL = REGISTRY.register("polished_limestone_wall", () -> new PolishedLimestoneWallBlock());
	public static final RegistryObject<Block> POLISHED_MARBLE_STAIRS = REGISTRY.register("polished_marble_stairs", () -> new PolishedMarbleStairsBlock());
	public static final RegistryObject<Block> POLISHED_MARBLE_SLAB = REGISTRY.register("polished_marble_slab", () -> new PolishedMarbleSlabBlock());
	public static final RegistryObject<Block> POLISHED_MARBLE_WALL = REGISTRY.register("polished_marble_wall", () -> new PolishedMarbleWallBlock());
	public static final RegistryObject<Block> POLISHED_QUARTZITE_STAIRS = REGISTRY.register("polished_quartzite_stairs", () -> new PolishedQuartziteStairsBlock());
	public static final RegistryObject<Block> POLISHED_QUARTZITE_SLAB = REGISTRY.register("polished_quartzite_slab", () -> new PolishedQuartziteSlabBlock());
	public static final RegistryObject<Block> POLISHED_QUARTZITE_WALL = REGISTRY.register("polished_quartzite_wall", () -> new PolishedQuartziteWallBlock());
	public static final RegistryObject<Block> POLISHED_SCORIA_STAIRS = REGISTRY.register("polished_scoria_stairs", () -> new PolishedScoriaStairsBlock());
	public static final RegistryObject<Block> POLISHED_SCORIA_SLAB = REGISTRY.register("polished_scoria_slab", () -> new PolishedScoriaSlabBlock());
	public static final RegistryObject<Block> POLISHED_SCORIA_WALL = REGISTRY.register("polished_scoria_wall", () -> new PolishedScoriaWallBlock());
	public static final RegistryObject<Block> CUT_TRAVERTINE_STAIRS = REGISTRY.register("cut_travertine_stairs", () -> new CutTravertineStairsBlock());
	public static final RegistryObject<Block> CUT_TRAVERTINE_SLAB = REGISTRY.register("cut_travertine_slab", () -> new CutTravertineSlabBlock());
	public static final RegistryObject<Block> CUT_TRAVERTINE_WALL = REGISTRY.register("cut_travertine_wall", () -> new CutTravertineWallBlock());
	public static final RegistryObject<Block> POLISHED_GREENSTONE_STAIRS = REGISTRY.register("polished_greenstone_stairs", () -> new PolishedGreenstoneStairsBlock());
	public static final RegistryObject<Block> POLISHED_GREENSTONE_SLAB = REGISTRY.register("polished_greenstone_slab", () -> new PolishedGreenstoneSlabBlock());
	public static final RegistryObject<Block> POLISHED_GREENSTONE_WALL = REGISTRY.register("polished_greenstone_wall", () -> new PolishedGreenstoneWallBlock());
	public static final RegistryObject<Block> ASHSTONE = REGISTRY.register("ashstone", () -> new AshstoneBlock());
	public static final RegistryObject<Block> COBBLED_ASHSTONE = REGISTRY.register("cobbled_ashstone", () -> new CobbledAshstoneBlock());
	public static final RegistryObject<Block> ASHSTONE_BRICKS = REGISTRY.register("ashstone_bricks", () -> new AshstoneBricksBlock());
	public static final RegistryObject<Block> ASHSTONE_BRICKS_STAIRS = REGISTRY.register("ashstone_bricks_stairs", () -> new AshstoneBricksStairsBlock());
	public static final RegistryObject<Block> ASHSTONE_BRICKS_SLAB = REGISTRY.register("ashstone_bricks_slab", () -> new AshstoneBricksSlabBlock());
	public static final RegistryObject<Block> ASHSTONE_BRICKS_WALL = REGISTRY.register("ashstone_bricks_wall", () -> new AshstoneBricksWallBlock());
	public static final RegistryObject<Block> ASHSTONE_STAIRS = REGISTRY.register("ashstone_stairs", () -> new AshstoneStairsBlock());
	public static final RegistryObject<Block> ASHSTONE_SLAB = REGISTRY.register("ashstone_slab", () -> new AshstoneSlabBlock());
	public static final RegistryObject<Block> ASHSTONE_WALL = REGISTRY.register("ashstone_wall", () -> new AshstoneWallBlock());
	public static final RegistryObject<Block> COBBLED_ASHSTONE_STAIRS = REGISTRY.register("cobbled_ashstone_stairs", () -> new CobbledAshstoneStairsBlock());
	public static final RegistryObject<Block> COBBLED_ASHSTONE_SLAB = REGISTRY.register("cobbled_ashstone_slab", () -> new CobbledAshstoneSlabBlock());
	public static final RegistryObject<Block> COBBLED_ASHSTONE_WALL = REGISTRY.register("cobbled_ashstone_wall", () -> new CobbledAshstoneWallBlock());
	public static final RegistryObject<Block> CRIMSONSTONE = REGISTRY.register("crimsonstone", () -> new CrimsonstoneBlock());
	public static final RegistryObject<Block> POLISHED_CRIMSONSTONE = REGISTRY.register("polished_crimsonstone", () -> new PolishedCrimsonstoneBlock());
	public static final RegistryObject<Block> CRIMSONSTONE_BRICKS = REGISTRY.register("crimsonstone_bricks", () -> new CrimsonstoneBricksBlock());
	public static final RegistryObject<Block> POLISHED_CRIMSONSTONE_STAIRS = REGISTRY.register("polished_crimsonstone_stairs", () -> new PolishedCrimsonstoneStairsBlock());
	public static final RegistryObject<Block> POLISHED_CRIMSONSTONE_SLAB = REGISTRY.register("polished_crimsonstone_slab", () -> new PolishedCrimsonstoneSlabBlock());
	public static final RegistryObject<Block> POLISHED_CRIMSONSTONE_WALL = REGISTRY.register("polished_crimsonstone_wall", () -> new PolishedCrimsonstoneWallBlock());
	public static final RegistryObject<Block> CRIMSONSTONE_BRICKS_STAIRS = REGISTRY.register("crimsonstone_bricks_stairs", () -> new CrimsonstoneBricksStairsBlock());
	public static final RegistryObject<Block> CRIMSONSTONE_BRICKS_SLAB = REGISTRY.register("crimsonstone_bricks_slab", () -> new CrimsonstoneBricksSlabBlock());
	public static final RegistryObject<Block> CRIMSONSTONE_BRICKS_WALL = REGISTRY.register("crimsonstone_bricks_wall", () -> new CrimsonstoneBricksWallBlock());
	public static final RegistryObject<Block> CRIMSONSTONE_STAIRS = REGISTRY.register("crimsonstone_stairs", () -> new CrimsonstoneStairsBlock());
	public static final RegistryObject<Block> CRIMSONSTONE_SLAB = REGISTRY.register("crimsonstone_slab", () -> new CrimsonstoneSlabBlock());
	public static final RegistryObject<Block> CRIMSONSTONE_WALL = REGISTRY.register("crimsonstone_wall", () -> new CrimsonstoneWallBlock());
	public static final RegistryObject<Block> DARK_BASALTSTONE = REGISTRY.register("dark_basaltstone", () -> new DarkBasaltstoneBlock());
	public static final RegistryObject<Block> DARK_BASALTSTONE_BRICKS = REGISTRY.register("dark_basaltstone_bricks", () -> new DarkBasaltstoneBricksBlock());
	public static final RegistryObject<Block> POLISHED_DARK_BASALTSTONE = REGISTRY.register("polished_dark_basaltstone", () -> new PolishedDarkBasaltstoneBlock());
	public static final RegistryObject<Block> DARK_BASALTSTONE_STAIRS = REGISTRY.register("dark_basaltstone_stairs", () -> new DarkBasaltstoneStairsBlock());
	public static final RegistryObject<Block> DARK_BASALTSTONE_SLAB = REGISTRY.register("dark_basaltstone_slab", () -> new DarkBasaltstoneSlabBlock());
	public static final RegistryObject<Block> DARK_BASALTSTONE_WALL = REGISTRY.register("dark_basaltstone_wall", () -> new DarkBasaltstoneWallBlock());
	public static final RegistryObject<Block> POLISHED_DARK_BASALTSTONE_STAIRS = REGISTRY.register("polished_dark_basaltstone_stairs", () -> new PolishedDarkBasaltstoneStairsBlock());
	public static final RegistryObject<Block> POLISHED_DARK_BASALTSTONE_SLAB = REGISTRY.register("polished_dark_basaltstone_slab", () -> new PolishedDarkBasaltstoneSlabBlock());
	public static final RegistryObject<Block> POLISHED_DARK_BASALTSTONE_WALL = REGISTRY.register("polished_dark_basaltstone_wall", () -> new PolishedDarkBasaltstoneWallBlock());
	public static final RegistryObject<Block> DARK_BASALTSTONE_BRICKS_STAIRS = REGISTRY.register("dark_basaltstone_bricks_stairs", () -> new DarkBasaltstoneBricksStairsBlock());
	public static final RegistryObject<Block> DARK_BASALTSTONE_BRICKS_SLAB = REGISTRY.register("dark_basaltstone_bricks_slab", () -> new DarkBasaltstoneBricksSlabBlock());
	public static final RegistryObject<Block> DARK_BASALTSTONE_BRICKS_WALL = REGISTRY.register("dark_basaltstone_bricks_wall", () -> new DarkBasaltstoneBricksWallBlock());
	public static final RegistryObject<Block> DEEPDAY = REGISTRY.register("deepday", () -> new DeepdayBlock());
	public static final RegistryObject<Block> COBBLED_DEEPDAY = REGISTRY.register("cobbled_deepday", () -> new CobbledDeepdayBlock());
	public static final RegistryObject<Block> POLISHED_DEEPDAY = REGISTRY.register("polished_deepday", () -> new PolishedDeepdayBlock());
	public static final RegistryObject<Block> DEEPDAY_BRICKS = REGISTRY.register("deepday_bricks", () -> new DeepdayBricksBlock());
	public static final RegistryObject<Block> DEEPDAY_TILES = REGISTRY.register("deepday_tiles", () -> new DeepdayTilesBlock());
	public static final RegistryObject<Block> DEEPDAY_STAIRS = REGISTRY.register("deepday_stairs", () -> new DeepdayStairsBlock());
	public static final RegistryObject<Block> DEEPDAY_SLAB = REGISTRY.register("deepday_slab", () -> new DeepdaySlabBlock());
	public static final RegistryObject<Block> DEEPDAY_WALL = REGISTRY.register("deepday_wall", () -> new DeepdayWallBlock());
	public static final RegistryObject<Block> POLISHED_DEEPDAY_STAIRS = REGISTRY.register("polished_deepday_stairs", () -> new PolishedDeepdayStairsBlock());
	public static final RegistryObject<Block> POLISHED_DEEPDAY_SLAB = REGISTRY.register("polished_deepday_slab", () -> new PolishedDeepdaySlabBlock());
	public static final RegistryObject<Block> POLISHED_DEEPDAY_WALL = REGISTRY.register("polished_deepday_wall", () -> new PolishedDeepdayWallBlock());
	public static final RegistryObject<Block> DEEPDAY_BRICKS_STAIRS = REGISTRY.register("deepday_bricks_stairs", () -> new DeepdayBricksStairsBlock());
	public static final RegistryObject<Block> DEEPDAY_BRICKS_SLAB = REGISTRY.register("deepday_bricks_slab", () -> new DeepdayBricksSlabBlock());
	public static final RegistryObject<Block> DEEPDAY_BRICKS_WALL = REGISTRY.register("deepday_bricks_wall", () -> new DeepdayBricksWallBlock());
	public static final RegistryObject<Block> DEEPDAY_TILES_STAIRS = REGISTRY.register("deepday_tiles_stairs", () -> new DeepdayTilesStairsBlock());
	public static final RegistryObject<Block> DEEPDAY_TILES_SLAB = REGISTRY.register("deepday_tiles_slab", () -> new DeepdayTilesSlabBlock());
	public static final RegistryObject<Block> DEEPDAY_TILES_WALL = REGISTRY.register("deepday_tiles_wall", () -> new DeepdayTilesWallBlock());
	public static final RegistryObject<Block> COBBLED_DEEPDAY_STAIRS = REGISTRY.register("cobbled_deepday_stairs", () -> new CobbledDeepdayStairsBlock());
	public static final RegistryObject<Block> COBBLED_DEEPDAY_SLAB = REGISTRY.register("cobbled_deepday_slab", () -> new CobbledDeepdaySlabBlock());
	public static final RegistryObject<Block> COBBLED_DEEPDAY_WALL = REGISTRY.register("cobbled_deepday_wall", () -> new CobbledDeepdayWallBlock());
	public static final RegistryObject<Block> FROSTSTONE = REGISTRY.register("froststone", () -> new FroststoneBlock());
	public static final RegistryObject<Block> POLISHED_FROSTSTONE = REGISTRY.register("polished_froststone", () -> new PolishedFroststoneBlock());
	public static final RegistryObject<Block> FROSTSTONE_STAIRS = REGISTRY.register("froststone_stairs", () -> new FroststoneStairsBlock());
	public static final RegistryObject<Block> FROSTSTONE_SLAB = REGISTRY.register("froststone_slab", () -> new FroststoneSlabBlock());
	public static final RegistryObject<Block> FROSTSTONE_WALL = REGISTRY.register("froststone_wall", () -> new FroststoneWallBlock());
	public static final RegistryObject<Block> POLISHED_FROSTSTONE_STAIRS = REGISTRY.register("polished_froststone_stairs", () -> new PolishedFroststoneStairsBlock());
	public static final RegistryObject<Block> POLISHED_FROSTSTONE_SLAB = REGISTRY.register("polished_froststone_slab", () -> new PolishedFroststoneSlabBlock());
	public static final RegistryObject<Block> POLISHED_FROSTSTONE_WALL = REGISTRY.register("polished_froststone_wall", () -> new PolishedFroststoneWallBlock());
	public static final RegistryObject<Block> MUDSTONE = REGISTRY.register("mudstone", () -> new MudstoneBlock());
	public static final RegistryObject<Block> COBBLED_MUDSTONE = REGISTRY.register("cobbled_mudstone", () -> new CobbledMudstoneBlock());
	public static final RegistryObject<Block> MUDSTONE_BRICKS = REGISTRY.register("mudstone_bricks", () -> new MudstoneBricksBlock());
	public static final RegistryObject<Block> MUDSTONE_STAIRS = REGISTRY.register("mudstone_stairs", () -> new MudstoneStairsBlock());
	public static final RegistryObject<Block> MUDSTONE_SLAB = REGISTRY.register("mudstone_slab", () -> new MudstoneSlabBlock());
	public static final RegistryObject<Block> MUDSTONE_WALL = REGISTRY.register("mudstone_wall", () -> new MudstoneWallBlock());
	public static final RegistryObject<Block> COBBLED_MUDSTONE_STAIRS = REGISTRY.register("cobbled_mudstone_stairs", () -> new CobbledMudstoneStairsBlock());
	public static final RegistryObject<Block> COBBLED_MUDSTONE_SLAB = REGISTRY.register("cobbled_mudstone_slab", () -> new CobbledMudstoneSlabBlock());
	public static final RegistryObject<Block> COBBLED_MUDSTONE_WALL = REGISTRY.register("cobbled_mudstone_wall", () -> new CobbledMudstoneWallBlock());
	public static final RegistryObject<Block> MUDSTONE_BRICKS_STAIRS = REGISTRY.register("mudstone_bricks_stairs", () -> new MudstoneBricksStairsBlock());
	public static final RegistryObject<Block> MUDSTONE_BRICKS_SLAB = REGISTRY.register("mudstone_bricks_slab", () -> new MudstoneBricksSlabBlock());
	public static final RegistryObject<Block> MUDSTONE_BRICKS_WALL = REGISTRY.register("mudstone_bricks_wall", () -> new MudstoneBricksWallBlock());
	public static final RegistryObject<Block> ROSESTONE = REGISTRY.register("rosestone", () -> new RosestoneBlock());
	public static final RegistryObject<Block> POLISHED_ROSESTONE = REGISTRY.register("polished_rosestone", () -> new PolishedRosestoneBlock());
	public static final RegistryObject<Block> ROSESTONE_STAIRS = REGISTRY.register("rosestone_stairs", () -> new RosestoneStairsBlock());
	public static final RegistryObject<Block> ROSESTONE_SLAB = REGISTRY.register("rosestone_slab", () -> new RosestoneSlabBlock());
	public static final RegistryObject<Block> ROSESTONE_WALL = REGISTRY.register("rosestone_wall", () -> new RosestoneWallBlock());
	public static final RegistryObject<Block> POLISHED_ROSESTONE_STAIRS = REGISTRY.register("polished_rosestone_stairs", () -> new PolishedRosestoneStairsBlock());
	public static final RegistryObject<Block> POLISHED_ROSESTONE_SLAB = REGISTRY.register("polished_rosestone_slab", () -> new PolishedRosestoneSlabBlock());
	public static final RegistryObject<Block> POLISHED_ROSESTONE_WAL = REGISTRY.register("polished_rosestone_wal", () -> new PolishedRosestoneWalBlock());
	public static final RegistryObject<Block> SILTSTONE = REGISTRY.register("siltstone", () -> new SiltstoneBlock());
	public static final RegistryObject<Block> CUT_SILTSTONE = REGISTRY.register("cut_siltstone", () -> new CutSiltstoneBlock());
	public static final RegistryObject<Block> SILTSTONE_STAIRS = REGISTRY.register("siltstone_stairs", () -> new SiltstoneStairsBlock());
	public static final RegistryObject<Block> SILTSTONE_SLAB = REGISTRY.register("siltstone_slab", () -> new SiltstoneSlabBlock());
	public static final RegistryObject<Block> SILTSTONE_WALL = REGISTRY.register("siltstone_wall", () -> new SiltstoneWallBlock());
	public static final RegistryObject<Block> CUT_SILTSTONE_STAIRS = REGISTRY.register("cut_siltstone_stairs", () -> new CutSiltstoneStairsBlock());
	public static final RegistryObject<Block> CUT_SILTSTONE_SLAB = REGISTRY.register("cut_siltstone_slab", () -> new CutSiltstoneSlabBlock());
	public static final RegistryObject<Block> CUT_SILTSTONE_WALL = REGISTRY.register("cut_siltstone_wall", () -> new CutSiltstoneWallBlock());
	public static final RegistryObject<Block> SUNSTONE = REGISTRY.register("sunstone", () -> new SunstoneBlock());
	public static final RegistryObject<Block> CUT_SUNSTONE = REGISTRY.register("cut_sunstone", () -> new CutSunstoneBlock());
	public static final RegistryObject<Block> SUNSTONE_STAIRS = REGISTRY.register("sunstone_stairs", () -> new SunstoneStairsBlock());
	public static final RegistryObject<Block> SUNSTONE_SLAB = REGISTRY.register("sunstone_slab", () -> new SunstoneSlabBlock());
	public static final RegistryObject<Block> SUNSTONE_WALL = REGISTRY.register("sunstone_wall", () -> new SunstoneWallBlock());
	public static final RegistryObject<Block> CUT_SUNSTONE_STAIRS = REGISTRY.register("cut_sunstone_stairs", () -> new CutSunstoneStairsBlock());
	public static final RegistryObject<Block> CUT_SUNSTONE_SLAB = REGISTRY.register("cut_sunstone_slab", () -> new CutSunstoneSlabBlock());
	public static final RegistryObject<Block> CUT_SUNSTONE_WALL = REGISTRY.register("cut_sunstone_wall", () -> new CutSunstoneWallBlock());
	public static final RegistryObject<Block> GABBRO_STAIRS = REGISTRY.register("gabbro_stairs", () -> new GabbroStairsBlock());
	public static final RegistryObject<Block> GABBRO_SLAB = REGISTRY.register("gabbro_slab", () -> new GabbroSlabBlock());
	public static final RegistryObject<Block> GABBRO_WALL = REGISTRY.register("gabbro_wall", () -> new GabbroWallBlock());
	public static final RegistryObject<Block> BASANITE_STAIRS = REGISTRY.register("basanite_stairs", () -> new BasaniteStairsBlock());
	public static final RegistryObject<Block> BASANITE_SLAB = REGISTRY.register("basanite_slab", () -> new BasaniteSlabBlock());
	public static final RegistryObject<Block> BASANITE_WALL = REGISTRY.register("basanite_wall", () -> new BasaniteWallBlock());
	public static final RegistryObject<Block> BASANITE_BRICKS_STAIRS = REGISTRY.register("basanite_bricks_stairs", () -> new BasaniteBricksStairsBlock());
	public static final RegistryObject<Block> BASANITE_BRICKS_SLAB = REGISTRY.register("basanite_bricks_slab", () -> new BasaniteBricksSlabBlock());
	public static final RegistryObject<Block> BASANITE_BRICKS_WALL = REGISTRY.register("basanite_bricks_wall", () -> new BasaniteBricksWallBlock());
	public static final RegistryObject<Block> LIMESTONE_STAIRS = REGISTRY.register("limestone_stairs", () -> new LimestoneStairsBlock());
	public static final RegistryObject<Block> LIMESTONE_SLAB = REGISTRY.register("limestone_slab", () -> new LimestoneSlabBlock());
	public static final RegistryObject<Block> LIMESTONE_WALL = REGISTRY.register("limestone_wall", () -> new LimestoneWallBlock());
	public static final RegistryObject<Block> MARBLE_STAIRS = REGISTRY.register("marble_stairs", () -> new MarbleStairsBlock());
	public static final RegistryObject<Block> MARBLE_SLAB = REGISTRY.register("marble_slab", () -> new MarbleSlabBlock());
	public static final RegistryObject<Block> MARBLE_WALL = REGISTRY.register("marble_wall", () -> new MarbleWallBlock());
	public static final RegistryObject<Block> QUARTZITE_STAIRS = REGISTRY.register("quartzite_stairs", () -> new QuartziteStairsBlock());
	public static final RegistryObject<Block> QUARTZITE_SLAB = REGISTRY.register("quartzite_slab", () -> new QuartziteSlabBlock());
	public static final RegistryObject<Block> QUARTZITE_WALL = REGISTRY.register("quartzite_wall", () -> new QuartziteWallBlock());
	public static final RegistryObject<Block> SCORIA_STAIRS = REGISTRY.register("scoria_stairs", () -> new ScoriaStairsBlock());
	public static final RegistryObject<Block> SCORIA_SLAB = REGISTRY.register("scoria_slab", () -> new ScoriaSlabBlock());
	public static final RegistryObject<Block> SCORIA_WALL = REGISTRY.register("scoria_wall", () -> new ScoriaWallBlock());
	public static final RegistryObject<Block> SCORIA_BRICKS_STAIRS = REGISTRY.register("scoria_bricks_stairs", () -> new ScoriaBricksStairsBlock());
	public static final RegistryObject<Block> SCORIA_BRICKS_SLAB = REGISTRY.register("scoria_bricks_slab", () -> new ScoriaBricksSlabBlock());
	public static final RegistryObject<Block> SCORIA_BRICKS_WALL = REGISTRY.register("scoria_bricks_wall", () -> new ScoriaBricksWallBlock());
	public static final RegistryObject<Block> SHALE_STAIRS = REGISTRY.register("shale_stairs", () -> new ShaleStairsBlock());
	public static final RegistryObject<Block> SHALE_SLAB = REGISTRY.register("shale_slab", () -> new ShaleSlabBlock());
	public static final RegistryObject<Block> SHALE_WALL = REGISTRY.register("shale_wall", () -> new ShaleWallBlock());
	public static final RegistryObject<Block> COBBLED_SHALE_STAIRS = REGISTRY.register("cobbled_shale_stairs", () -> new CobbledShaleStairsBlock());
	public static final RegistryObject<Block> COBBLED_SHALE_SLAB = REGISTRY.register("cobbled_shale_slab", () -> new CobbledShaleSlabBlock());
	public static final RegistryObject<Block> COBBLED_SHALE_WALL = REGISTRY.register("cobbled_shale_wall", () -> new CobbledShaleWallBlock());
	public static final RegistryObject<Block> SHALE_BRICKS = REGISTRY.register("shale_bricks", () -> new ShaleBricksBlock());
	public static final RegistryObject<Block> SHALE_BRICKS_STAIRS = REGISTRY.register("shale_bricks_stairs", () -> new ShaleBricksStairsBlock());
	public static final RegistryObject<Block> SHALE_BRICKS_SLAB = REGISTRY.register("shale_bricks_slab", () -> new ShaleBricksSlabBlock());
	public static final RegistryObject<Block> SHALE_BRICKS_WALL = REGISTRY.register("shale_bricks_wall", () -> new ShaleBricksWallBlock());
	public static final RegistryObject<Block> SLATE_BRICKS = REGISTRY.register("slate_bricks", () -> new SlateBricksBlock());
	public static final RegistryObject<Block> SLATE_STAIRS = REGISTRY.register("slate_stairs", () -> new SlateStairsBlock());
	public static final RegistryObject<Block> SLATE_SLAB = REGISTRY.register("slate_slab", () -> new SlateSlabBlock());
	public static final RegistryObject<Block> SLATE_WALL = REGISTRY.register("slate_wall", () -> new SlateWallBlock());
	public static final RegistryObject<Block> COBBLED_SLATE_SLAB = REGISTRY.register("cobbled_slate_slab", () -> new CobbledSlateSlabBlock());
	public static final RegistryObject<Block> COBBLED_SLATE_STAIRS = REGISTRY.register("cobbled_slate_stairs", () -> new CobbledSlateStairsBlock());
	public static final RegistryObject<Block> COBBLED_SLATE_WALL = REGISTRY.register("cobbled_slate_wall", () -> new CobbledSlateWallBlock());
	public static final RegistryObject<Block> SLATE_BRICKS_STAIRS = REGISTRY.register("slate_bricks_stairs", () -> new SlateBricksStairsBlock());
	public static final RegistryObject<Block> SLATE_BRICKS_SLAB = REGISTRY.register("slate_bricks_slab", () -> new SlateBricksSlabBlock());
	public static final RegistryObject<Block> SLATE_BRICKS_WALL = REGISTRY.register("slate_bricks_wall", () -> new SlateBricksWallBlock());
	public static final RegistryObject<Block> TRAVERTINE_STAIRS = REGISTRY.register("travertine_stairs", () -> new TravertineStairsBlock());
	public static final RegistryObject<Block> TRAVERTINE_SLAB = REGISTRY.register("travertine_slab", () -> new TravertineSlabBlock());
	public static final RegistryObject<Block> TRAVERTINE_WALL = REGISTRY.register("travertine_wall", () -> new TravertineWallBlock());
	public static final RegistryObject<Block> GREENSTONE_STAIRS = REGISTRY.register("greenstone_stairs", () -> new GreenstoneStairsBlock());
	public static final RegistryObject<Block> GREENSTONE_SLAB = REGISTRY.register("greenstone_slab", () -> new GreenstoneSlabBlock());
	public static final RegistryObject<Block> GREENSTONE_WALL = REGISTRY.register("greenstone_wall", () -> new GreenstoneWallBlock());
	// Start of user code block custom blocks
	// End of user code block custom blocks
}